name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build release binary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo build --release
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/lighturlshortener
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
